version: '3'

networks:
  project:

services:
  backend:
    container_name: backend
    # will build ./docker/web/Dockerfile
    ports:
      - "8080:8080"
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    networks:
      - project
  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=wintercurse12347890
    networks:
      - project